### ISSUE TITLE
taro3.0使用 foca-taro-storage 报错

### ISSUE THREAD

**Issue by huangbh1024** [foca-js/foca-taro-storage#1]
微信开发者工具可以正常运行，但是真机调试报错，------没有找到页面实例

**Comment by geekact** [comment]
现在应该是彻底解决了，升级到v0.1.2

**Comment by geekact** [comment]
也可以看下我在taro官方issue下的说明：https://github.com/NervJS/taro/issues/6548#issuecomment-1097783013

**Comment by geekact** [comment]
现在通过hack的形式完美解决了，开发者不用增加任何代码，只需升级到 v1.0.0

**Comment by smithyj** [comment]
能给个案例？怎么配置呢？

**Comment by geekact** [comment]
> 能给个案例？怎么配置呢？
@smithyj 

https://github.com/foca-js/foca-demo-taro/blob/master/src/store.ts#L26
https://github.com/foca-js/foca-demo-taro/blob/master/src/app.tsx#L16
